gpu_id: ""
seed: 10000
display: True
im_size: 32

diffusion:
  target: models.script_util.create_gaussian_diffusion
  params:
    steps: 1000
    learn_sigma: True
    sigma_small: False
    noise_schedule: cosine
    use_kl: False
    predict_xstart: False
    rescale_timesteps: False
    rescale_learned_sigmas: True
    timestep_respacing: "1000"

model:
  target: models.unet.UNetModel
  ckpt_path: weights/diffusion/cifar10_uncond_vlb_50M_500K.pt
  params:
    image_size: 32
    in_channels: 3
    model_channels: 128
    out_channels: 6
    attention_resolutions: [16, 8]
    dropout: 0.3
    channel_mult: [1, 2, 2, 2]
    num_res_blocks: 3
    conv_resample: True
    dims: 2
    use_fp16: False
    num_head_channels: 64
    use_scale_shift_norm: True
    resblock_updown: False
    use_new_attention_order: False

model_ir:
  target: models.lama.ffc.FFCResNetGenerator
  ckpt_path: weights/estimator/lama_inpainting256.pth
  params:
    input_nc: 4
    output_nc: 3
    ngf: 64
    n_downsampling: 3
    n_blocks: 18
    add_out_act: sigmoid
    init_conv_kwargs:
      ratio_gin: 0
      ratio_gout: 0
      enable_lfu: false
    downsample_conv_kwargs:
      ratio_gin: ${model_ir.params.init_conv_kwargs.ratio_gout}
      ratio_gout: ${model_ir.params.downsample_conv_kwargs.ratio_gin}
      enable_lfu: False
    resnet_conv_kwargs:
      ratio_gin: 0.75
      ratio_gout: ${model_ir.params.resnet_conv_kwargs.ratio_gin}
      enable_lfu: False
